server:
  port: 3001
  info: "这是提供者的yml"

spring:
  application:
    name: users-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    
#熔断
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/

  
